// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJiRLwZejZmnqFAltBCoNlEJPYxkm1MgM',
    appId: '1:1094142334808:web:d3f8ab25c49a5f4a0d372d',
    messagingSenderId: '1094142334808',
    projectId: 'petshop-eduardo',
    authDomain: 'petshop-eduardo.firebaseapp.com',
    storageBucket: 'petshop-eduardo.firebasestorage.app',
    measurementId: 'G-PT4S65ELYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2YXL8ed2dMQ50MDmMOcA1yWn3wvSsJ_M',
    appId: '1:1094142334808:android:90f8fe8030c2fa390d372d',
    messagingSenderId: '1094142334808',
    projectId: 'petshop-eduardo',
    storageBucket: 'petshop-eduardo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL858TD4OC4-fSl9IOGa4Qdt7XJxCC4Wk',
    appId: '1:1094142334808:ios:5a4e66f52f3c5ed80d372d',
    messagingSenderId: '1094142334808',
    projectId: 'petshop-eduardo',
    storageBucket: 'petshop-eduardo.firebasestorage.app',
    iosBundleId: 'com.example.petShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL858TD4OC4-fSl9IOGa4Qdt7XJxCC4Wk',
    appId: '1:1094142334808:ios:5a4e66f52f3c5ed80d372d',
    messagingSenderId: '1094142334808',
    projectId: 'petshop-eduardo',
    storageBucket: 'petshop-eduardo.firebasestorage.app',
    iosBundleId: 'com.example.petShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJiRLwZejZmnqFAltBCoNlEJPYxkm1MgM',
    appId: '1:1094142334808:web:2c34aa126a4ed3200d372d',
    messagingSenderId: '1094142334808',
    projectId: 'petshop-eduardo',
    authDomain: 'petshop-eduardo.firebaseapp.com',
    storageBucket: 'petshop-eduardo.firebasestorage.app',
    measurementId: 'G-B8Q4J9M6W8',
  );
}
